language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_install:
  - sudo apt-get install python-capstone

script:
  - python tests.py
